theme: jekyll-theme-slate
title: Taller Amentúrate ¿Cómo juega un computador al ajedrez
y por qué no puedo ganarle?
description: Página web con enlaces a recursos y elementos comentados durante 
             la celebración del taller de Amentúrate ¿Cómo juega un computador 
             al ajedrez y por qué no puedo ganarle?

