theme: jekyll-theme-slate
title: ¿Cómo juega un computador al ajedrez y por qué no puedo ganarle?
description: >-
  Esta página contiene el material utilizado para impartir el taller del programa Amentúrate *¿Cómo juega un computador al ajedrez y por qué no puedo ganarle?*, así enlaces a diferentes elementos referidos durante el desarrollo de dicho taller.
