theme: jekyll-theme-slate
title: ¿Cómo juega un computador al ajedrez y por qué no puedo ganarle?
description: >-
  Esta página contiene el material utilizado para impartir el taller del programa Amentúrate <em>¿Cómo juega un computador al ajedrez y por qué no puedo ganarle?</em>, así como enlaces a diferentes elementos referidos durante el desarrollo de dicho taller.

twitter: pabloUnican
email: p.sanchez@unican.es
